import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope } from "next/font/google";
import "./globals.css";
import styles from "@/app/layout.module.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { ReactNode } from "react";


const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="fr">
      <body className={`${manrope.variable}`}>

        <div className={styles.page}>
          <Header />
          <main className={styles.mainContent}>
            <div className={styles.contentWrapper}>
              {children}
            </div>
          </main>
          <Footer />
        </div>

      </body>
    </html>
  );
}
